### ISSUE TITLE
Error while trying to play

### ISSUE THREAD

**Issue by mrsaraiva** [vitorhirota/plugin.video.globotv#10]
Hi,

Using the latest version from the repository, i get the error message: "Player not recognized. Globo.tv". This started today, 28/01.

Thanks

**Comment by max-vmcode** [comment]
Hi Marcos,
As the author moved to bitbucket you have to open your issue there.
Btw, me too I'm getting your error..but this happened this afternoon as this morning my wife was able to watch their favourite novela.

Cheers
Max
