### ISSUE TITLE
Hash question

### ISSUE THREAD

**Issue by denobisipsis** [vitorhirota/plugin.video.globotv#12]
Hi Vitor,

you don't need to mimic the js behavior, just think that the I function runs the md5 algorithm.
Just make base64.b64encode(hashlib.md5())

**Comment by vitorhirota** [comment]
Wow, really? This is a great catch if true! Have you run some tests? I'll try it as soon as I have some time.

**Comment by denobisipsis** [comment]
Yes, it works, in php

Think $hash is the received hash, then

```
            $receivedTime    =substr($hash,2,10);
            $receivedRandom    =substr($hash,12,10);
            $receivedMD5    =substr($hash,22,22);

            $padding=randomPadding();// 10 random digits

            $newmd5
```

=base64_encode(md5($receivedMD5.($receivedTime+3600).$padding.$salt,true));

secure the base64_encode and cut off the last 2 characters (normaly ==)

```
            $newmd5
```

=substr(str_replace(array("+","/"),array("-","_"),$newmd5),0,-2);

normally begins with 0502

```
            $hash
```

="0502".$receivedTime.$receivedRandom.($receivedTime+3600).$padding.$newmd5;

That's all

The salt ("0xAC10FD") maybe can be another, 0xFF01DD for flash

```
            $mp4    =$url."?h=$hash&k=app";
```

Reduce the code

Test it

2014-07-01 22:56 GMT+02:00 vitorhirota notifications@github.com:

**Comment by vitorhirota** [comment]
What an awesome finding! Thanks for the heads up!

**Comment by vitorhirota** [comment]
@denobis, just to thank you once again for this great tip. I've tested it and it seems to be exactly what you said. Thanks again!
