### ISSUE TITLE
Script failed! 

### ISSUE THREAD

**Issue by lolobest** [vitorhirota/plugin.video.globotv#2]
Problem of script failed XBMC no Galaxy S2 android jelly Bean.

**Comment by vitorhirota** [comment]
Tem o log?

**Comment by lolobest** [comment]
Eu tentei achar o log aqui no android, mas não encontrei. Porem hoje
configurei usuário  senha no plugin e consigo assistir agora. Não tinha
configurado antes porque no galaxy note 10.1 tinha ido de boa, pegando as
configurações dl chrome eu acho. Obrigado pela resposta.
Em 28/01/2013 19:38, "vitorhirota" notifications@github.com escreveu:

**Comment by vitorhirota** [comment]
Se acontecer de novo, posta um gist aqui que eu dou uma olhada.
