### ISSUE TITLE
Script error on XBMC Frodo

### ISSUE THREAD

**Issue by bolleboll** [vitorhirota/plugin.video.globotv#4]
Hi.

Thank you for an excellent application.

I am trying to use the script on XBMC 12.0 Frodo, and i get a script error when starting a stream. 
Looks like a StorageServer script is used that is not compatible with Frodo...
Anything you have seen before?

22:58:06 T:2859172960  NOTICE: [globotv] authenticate: successfully authenticated
22:58:06 T:2859172960  NOTICE: [globotv] <module>: Params: {'action': 'play', 'video_id': '2386697'}
22:58:08 T:2859172960  NOTICE: [globotv] get_hashes: video id: 2386697, resource ids: 51104fff9214476489000665|5110558c921447647d0006a1|51105405921447648400079a|51105d5e9214476493000691
22:58:08 T:2859172960  NOTICE: [globotv] get_hashes: hashes: {"hash":["0313638294026704737240n+zhH9FI+7Tj4Yjknq1n0w","0313638294023444016705Jkb+vRK2aEm5+AUS5YyBXw","03136382940229915987228/bs6AuI2Ac1WZ/H0Zs++g","0313638294027056072968CP8b+GO475C+go+0hnZ0GA"],"product":"Globo Mídia 3.0 - 500"}
22:58:09 T:2944230496   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: unsupported operand type(s) for +: 'int' and 'str'
                                            Traceback (most recent call last):
                                              File "/storage/.xbmc/addons/script.common.plugin.cache/default.py", line 40, in <module>
                                                run()
                                              File "/storage/.xbmc/addons/script.common.plugin.cache/default.py", line 35, in run
                                                s.run()
                                              File "/storage/.xbmc/addons/script.common.plugin.cache/lib/StorageServer.py", line 232, in run
                                                self._runCommand(data)
                                              File "/storage/.xbmc/addons/script.common.plugin.cache/lib/StorageServer.py", line 164, in _runCommand
                                                res = self._sqlGet(data["table"], data["name"])
                                              File "/storage/.xbmc/addons/script.common.plugin.cache/lib/StorageServer.py", line 423, in _sqlGet
                                                self._log(name + " - " + table, 2)
                                            TypeError: unsupported operand type(s) for +: 'int' and 'str'
                                            -->End of Python script error report<--

StorageServer.py

```
def _sqlGet(self, table, name):
    self._log(name + " - " + table, 2)

    self._checkTable(table)
    self._sqlExecute("SELECT data FROM " + table + " WHERE name = %s", name)

    for row in self.curs:
        self._log("Returning : " + str(repr(row[0]))[0:20], 3)
        return row[0]

    self._log("Returning empty", 3)
    return " "
```

Cheers
Bolleboll

**Comment by vitorhirota** [comment]
Bolleboll, you can't watch to any videos, is that right?

This error you point out is expected and dealt with in the plug-in. It was a bad decision while coding, and I'm revising it for a next version. There's more details on issue #1's first comments

**Comment by bolleboll** [comment]
Hi.

That is correct, i do not seem to be able to watch any video.
i am just given the script error output and the stream looks like it is trying to start.
I have to hit the cancel button to go back.

It sounds excellent that a revision is planned.
Looking forward to it..
