### ISSUE TITLE
Unable to install version 0.5

### ISSUE THREAD

**Issue by Olivier49** [vitorhirota/plugin.video.globotv#5]
Hi Vitor,

Thanks a lot for the update.
But unfortunately, I am not able to install it. In XBMC I get a "Dependencies not met" and the logs(logvel=1) show:

16:19:42 T:140356870584192   DEBUG: GetZipList - Processing zip://%2fhome%2folivebuntu%2fBureau%2fplugin.video.globotv-master.zip/
16:19:42 T:140356870584192   DEBUG: Addon plugin.video.globotv requires script.module.requests version 1.0.4 which is not available

The plugin needs requests module.

I tried on my HTPC (Xtreamer ultra) with XBMC 11 (running on Openelec).
I also tried on my Laptop running Ubuntu 12.04, XBMC 11 and then tried a nighty build XBMC 13, but I still got this error message.

Thanks
Regards,

Olivier

**Comment by vitorhirota** [comment]
Olivier, commit 9d946ab86b573724cf425ec5211ac89085752bbb has just been pushed fixing a backwards compatibility for Eden.

The plugin was configured with a newer version of the script.module.requests dependency, only available for Frodo. It has been corrected, along with a method call of xbmc.gui also only available for Frodo.

You can get the fixed addon here: https://github.com/vitorhirota/plugin.video.globotv/archive/plugin.video.globotv-0.5.1.zip

**Comment by vitorhirota** [comment]
Just a side note, I forgot to actually test play functionality. So commit 5b5ea1ce78e08ca600212ae8bc18f029a288bdf1 is in, to fix the rest... Tag e download link relocated.

**Comment by Olivier49** [comment]
Thanks Vitor, I could install version 0.5.1 ;)
I tried to see Salve Jorge, from 13/02, 12/02 and 11/02 but got these errors:

http://pastebin.com/raw.php?i=i87a9yrL

Thanks again !

Olivier

**Comment by vitorhirota** [comment]
Olivier, I've tried to replicate the error on your log, but had no success.
Both on Eden and Frodo it ran just fine the video with id 2404983.
Apparently it's been failing during the debug log call due to an unhandled unicode character. 
One idea is to just disable the debug, or comment out the lines on the py file.

**Comment by Olivier49** [comment]
Hi Vitor,

Thanks again. I switched back to the default loglevel, for both Frodo and Eden and I was able to watch some "Salve Jorge" novelas, but "Lado a Lado" does not work.

Here's the log: http://pastebin.com/raw.php?i=fA26Zm6R

It seems that, no matter if I go into the plugin settings and set the username/password for subscribers (assinantes), the plugin will still play the free stream, the iphone360 one.

Thanks again,

Olivier

**Comment by vitorhirota** [comment]
Olivier, is the plugin configured with the option 'HD when available' for
the Video Quality setting?

**Comment by Olivier49** [comment]
Hey Vitor,

Yes, HD when available, and I checked the settings.xml:

```
<setting id="video_quality" value="1" />
```

Thanks,
Regards,

Olivier

**Comment by vitorhirota** [comment]
Olivier, on resources.lib.globo.py, line 62, substitute with the following:

```
self.plugin.log.debug('return: %s' % req.text.encode('ascii', 'replace'))
```

This might suppress the error and actually log what it's trying to log.

You may turn the debug on again and post me back the log.

**Comment by Olivier49** [comment]
Thanks a lot, it works fine now, HD for every novelas I tried, cheers ;)

**Comment by Olivier49** [comment]
Actually, it worked fine when I commented out line 62, but with replace: http://pastebin.com/raw.php?i=bXNpNsQy
but that's fine, it works fine with this line commented out ;)

Thanks again.

**Comment by Olivier49** [comment]
self.plugin.log.debug('return: %s' % req.text.encode('ascii', 'replace'))

works fine, sorry for spam...

**Comment by vitorhirota** [comment]
ops, my bad with the pasted code... just corrected it...

**Comment by vitorhirota** [comment]
awesome, glad it worked out
