### ISSUE TITLE
THANK YOU!

### ISSUE THREAD

**Issue by max-vmcode** [vitorhirota/plugin.video.globotv#7]
I know that this could not be the right place where writing to you but yesterday I was finally able to test your new plugin version and it's wonderful! I even do not know how to thank you for your incredible work as this plugin is perfect!

Muito obrigado
Massimo

Se vocè passa em Milao na Italia vou te agradeçer pessoalmente!

**Comment by vitorhirota** [comment]
No problem Massimo. I'm just glad to hear it worked! Enjoy.

Saluti!
